version: 0.0
os: linux

files:
  - source: backend/target/Finsmart_Finances-0.0.1-SNAPSHOT.jar
    destination: /opt/finsmart/

hooks:
  ApplicationStart:
    - location: backend/scripts/start.sh
      timeout: 60
