version: 0.0
os: linux

files:
  - source: target/FinSmart_Finances-0.0.1-SNAPSHOT.jar
    destination: /opt/finsmart/

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
