version: 0.2

phases:
  install:
    commands:
      - yum install maven -y

  build:
    commands:
      - echo "Entering backend folder"
      - cd backend
      - echo "Building Spring Boot project..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - backend/target/Finsmart_Finances-0.0.1-SNAPSHOT.jar
    - backend/appspec.yaml
    - backend/scripts/*
